import { DbcDatabase } from '../types/can';

export interface SchemaPreset {
  id: string;
  name: string;
  description: string;
  category: 'Automotive' | 'EV & BMS' | 'Robotics' | 'Industrial';
  database: DbcDatabase;
}

export const SCHEMA_PRESETS: SchemaPreset[] = [
  {
    id: 'automotive-chassis',
    name: 'Automotive Powertrain & Chassis',
    category: 'Automotive',
    description: 'Standard ICE/Hybrid telemetry: Engine RPM, Throttle, Vehicle Speed, and Brake Pressure.',
    database: {
      filename: 'Automotive_Powertrain.json',
      version: '1.0',
      messages: [
        {
          id: 0x100,
          idHex: '0x100',
          name: 'Engine_Status',
          dlc: 8,
          transmitter: 'POWERTRAIN_ECU',
          comment: 'Core engine telemetry and rolling heartbeat',
          signals: [
            {
              name: 'EngineRPM',
              startBit: 0,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 0.25,
              offset: 0,
              min: 0,
              max: 8000,
              unit: 'rpm',
              receivers: ['DASHBOARD', 'TELEMATICS'],
            },
            {
              name: 'EngineCoolantTemp',
              startBit: 16,
              length: 8,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 1,
              offset: -40,
              min: -40,
              max: 150,
              unit: '°C',
              receivers: ['DASHBOARD'],
            },
            {
              name: 'EngineTorque',
              startBit: 24,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: true,
              scale: 0.1,
              offset: -200,
              min: -200,
              max: 500,
              unit: 'Nm',
              receivers: ['TRANSMISSION'],
            },
            {
              name: 'ThrottlePosition',
              startBit: 40,
              length: 8,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 0.4,
              offset: 0,
              min: 0,
              max: 100,
              unit: '%',
              receivers: ['POWERTRAIN_ECU'],
            },
            {
              name: 'CheckEngineLight',
              startBit: 48,
              length: 1,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 1,
              offset: 0,
              min: 0,
              max: 1,
              unit: '',
              receivers: ['DASHBOARD'],
            },
          ],
        },
        {
          id: 0x120,
          idHex: '0x120',
          name: 'Brake_And_Steering',
          dlc: 8,
          transmitter: 'ABS_ESP_ECU',
          comment: 'Wheel speeds, steering wheel angle, and brake pressure',
          signals: [
            {
              name: 'VehicleSpeed',
              startBit: 0,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 0.01,
              offset: 0,
              min: 0,
              max: 250,
              unit: 'km/h',
              receivers: ['DASHBOARD', 'POWERTRAIN'],
            },
            {
              name: 'BrakePressure',
              startBit: 16,
              length: 8,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 0.5,
              offset: 0,
              min: 0,
              max: 100,
              unit: 'bar',
              receivers: ['POWERTRAIN'],
            },
            {
              name: 'SteeringAngle',
              startBit: 24,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: true,
              scale: 0.1,
              offset: 0,
              min: -540,
              max: 540,
              unit: 'deg',
              receivers: ['ESP_CONTROLLER'],
            },
          ],
        },
      ],
    },
  },
  {
    id: 'ev-bms',
    name: 'Electric Vehicle High-Voltage BMS',
    category: 'EV & BMS',
    description: 'Traction battery pack voltage, current, state of charge (SoC), and thermal safety limits.',
    database: {
      filename: 'EV_Battery_BMS.json',
      version: '1.0',
      messages: [
        {
          id: 0x200,
          idHex: '0x200',
          name: 'BMS_Pack_Metrics',
          dlc: 8,
          transmitter: 'BMS_MASTER',
          comment: 'Primary traction battery telemetry',
          signals: [
            {
              name: 'PackVoltage',
              startBit: 0,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 0.1,
              offset: 0,
              min: 0,
              max: 800,
              unit: 'V',
              receivers: ['INVERTER', 'CHARGER'],
            },
            {
              name: 'PackCurrent',
              startBit: 16,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: true,
              scale: 0.1,
              offset: 0,
              min: -500,
              max: 500,
              unit: 'A',
              receivers: ['INVERTER'],
            },
            {
              name: 'StateOfCharge',
              startBit: 32,
              length: 8,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 0.5,
              offset: 0,
              min: 0,
              max: 100,
              unit: '%',
              receivers: ['DASHBOARD', 'VCU'],
            },
            {
              name: 'MaxCellTemp',
              startBit: 40,
              length: 8,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 1,
              offset: -40,
              min: -40,
              max: 120,
              unit: '°C',
              receivers: ['THERMAL_MANAGEMENT'],
            },
            {
              name: 'HighVoltageInterlock',
              startBit: 48,
              length: 1,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 1,
              offset: 0,
              min: 0,
              max: 1,
              unit: '',
              receivers: ['SAFETY_SYSTEM'],
            },
          ],
        },
      ],
    },
  },
  {
    id: 'robotics-joint',
    name: 'Robotics CAN Servo Actuator',
    category: 'Robotics',
    description: 'Brushless motor feedback: target position, measured position, velocity, and winding temp.',
    database: {
      filename: 'Robotics_Joint_Servo.json',
      version: '1.0',
      messages: [
        {
          id: 0x301,
          idHex: '0x301',
          name: 'Joint_1_Telemetry',
          dlc: 8,
          transmitter: 'SERVO_JOINT_1',
          comment: 'Joint encoder feedback and motor diagnostics',
          signals: [
            {
              name: 'JointAngle',
              startBit: 0,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: true,
              scale: 0.01,
              offset: 0,
              min: -180,
              max: 180,
              unit: 'deg',
              receivers: ['MOTION_CONTROLLER'],
            },
            {
              name: 'JointVelocity',
              startBit: 16,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: true,
              scale: 0.1,
              offset: 0,
              min: -500,
              max: 500,
              unit: 'deg/s',
              receivers: ['MOTION_CONTROLLER'],
            },
            {
              name: 'TorqueCurrent',
              startBit: 32,
              length: 16,
              byteOrder: 'little_endian',
              isSigned: true,
              scale: 0.01,
              offset: 0,
              min: -30,
              max: 30,
              unit: 'A',
              receivers: ['MOTION_CONTROLLER'],
            },
            {
              name: 'MotorTemp',
              startBit: 48,
              length: 8,
              byteOrder: 'little_endian',
              isSigned: false,
              scale: 1,
              offset: 0,
              min: 0,
              max: 120,
              unit: '°C',
              receivers: ['SAFETY_SYSTEM'],
            },
          ],
        },
      ],
    },
  },
];
