import { CanFrame } from '../types/can';

/**
 * Formats a timestamp into Vector .asc header date string.
 * Example: Mon Sep 14 09:30:00.000 pm 2026
 */
function formatAscHeaderDate(date: Date): string {
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const dayName = days[date.getDay()];
  const monthName = months[date.getMonth()];
  const day = String(date.getDate()).padStart(2, '0');
  let hours = date.getHours();
  const ampm = hours >= 12 ? 'pm' : 'am';
  hours = hours % 12 || 12;
  const hoursStr = String(hours).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  const seconds = String(date.getSeconds()).padStart(2, '0');
  const millis = String(date.getMilliseconds()).padStart(3, '0');
  const year = date.getFullYear();

  return `${dayName} ${monthName} ${day} ${hoursStr}:${minutes}:${seconds}.${millis} ${ampm} ${year}`;
}

/**
 * Exports an array of CanFrame objects into standard Vector Informatik ASCII (.asc) format.
 * Compatible with Vector CANoe, CANalyzer, PCAN-View, Wireshark, and SavvyCAN.
 */
export function exportToVectorAsc(frames: CanFrame[], channelNum = 1): string {
  const now = new Date();
  const lines: string[] = [
    `date ${formatAscHeaderDate(now)}`,
    'base hex  timestamps absolute',
    'internal events logged',
    '// version 8.1.0 (Generated by CANScope Automotive Diagnostic Platform)',
  ];

  const firstTimestamp = frames.length > 0 ? frames[0].timestamp : 0;

  for (const f of frames) {
    // Relative timestamp from first frame, or absolute seconds
    const relTime = Math.max(0, f.timestamp - firstTimestamp).toFixed(6);
    const dir = f.direction === 'TX' ? 'Tx' : 'Rx';
    const idClean = f.idHex.replace(/^0x/i, '').toUpperCase();
    const idWithExt = f.extended ? `${idClean}x` : idClean;

    if (f.fd) {
      // Vector CAN-FD syntax:
      // <timestamp> CANFD <channel> <Rx|Tx> <id> <brs> <esi> <dlc> <data bytes...> 0 0 <baud1> <baud2>
      const brsFlag = f.brs ? 1 : 0;
      const esiFlag = 0;
      const dataBytes = f.data.map((b) => b.toString(16).toUpperCase().padStart(2, '0')).join(' ');
      lines.push(
        `${relTime.padStart(10, ' ')} CANFD   ${channelNum} ${dir} ${idWithExt.padEnd(8, ' ')} ${brsFlag} ${esiFlag} ${f.dlc.toString().padStart(2, ' ')} ${dataBytes}`
      );
    } else {
      // Standard CAN 2.0A/B syntax:
      // <timestamp> <channel> <id> <Rx|Tx> d <dlc> <data bytes...>
      const dataBytes = f.data.map((b) => b.toString(16).toUpperCase().padStart(2, '0')).join(' ');
      lines.push(
        `${relTime.padStart(10, ' ')} ${channelNum}  ${idWithExt.padEnd(14, ' ')} ${dir.padEnd(4, ' ')} d ${f.dlc} ${dataBytes}`
      );
    }
  }

  lines.push('// End of CANScope Vector ASC Trace Log');
  return lines.join('\n');
}

/**
 * Exports an array of CanFrame objects into standard SocketCAN candump log format.
 * Compatible with Linux can-utils (candump, canplayer, canlogserver, wireshark).
 * Format: (<epoch_timestamp>) <interface> <ID>#<DATA> or <ID>##<FLAGS><DATA> for CAN-FD
 */
export function exportToSocketCanDump(frames: CanFrame[], iface = 'can0'): string {
  const lines: string[] = [];

  for (const f of frames) {
    const tsStr = f.timestamp.toFixed(6);
    const idClean = f.idHex.replace(/^0x/i, '').toUpperCase();
    const dataHex = f.data.map((b) => b.toString(16).toUpperCase().padStart(2, '0')).join('');

    if (f.fd) {
      // CAN-FD in candump uses ## with flags (1 for BRS, 0 for standard FD)
      const flags = f.brs ? '1' : '0';
      lines.push(`(${tsStr}) ${iface} ${idClean}##${flags}${dataHex}`);
    } else {
      // Standard Classic CAN
      lines.push(`(${tsStr}) ${iface} ${idClean}#${dataHex}`);
    }
  }

  return lines.join('\n');
}

/**
 * Trigger browser file download with blob memory release
 */
export function downloadFile(content: string, filename: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
